### ISSUE TITLE
Funkcja obliczająca NWD

### ISSUE THREAD

**Issue by edek1205** [lukaszex/Wolphram-omega#15]

**Comment by arkaleta** [comment]
Napisałem funkcję obliczającą NWD dwóch liczb i dołączyłem ją do pliku .cpp w repozytorium. Nie napotkałem większych problemów, sprawdzałem program i wszystko działa. Zalecam aby w main-ie zamieścić poszczególne case-y w osobnych funkcjach, aby nie tworzyć zbyt dużo zmiennych.

**Comment by edek1205** [comment]
Ok, dzięki..
