### ISSUE TITLE
Podsumowanie sprintu 02.05.2017

### ISSUE THREAD

**Issue by przykladowystudent2017** [lukaszex/Wolphram-omega#5]
Utworzono w celu podsumowania tygodniowego sprintu. Tutaj wpisujemy co udało nam się osiągnąć przez ostatni tydzień, jakie mamy plany na kolejny sprint

**Comment by przykladowystudent2017** [comment]
Propozycja: milestone na kolejny sprint to stworzenie Backlog produktu? Co o tym sądzicie

**Comment by lukaszex** [comment]
W czwartek i piątek zacząłem czytać podręcznik Praty. Uznałem, że nie ma sensu uczyć się powtórnie elementów znanych już z języka C, więc zacząłem od zmiennych referencyjnych i przeciążania funkcji. W sobotę zachorowałem na grypę i przez cztery kolejne dni nie byłem w stanie wstać z łóżka. Dopiero we wtorek udało mi się poczytać rozdział o klasach, w tym także m.in. konstruktorach, destruktorach i wskaźniku this.

**Comment by edek1205** [comment]
Ja zacząłem od samego początku, wykorzystując podręczniki Stephena Prata i Jerzego Grębosza. Przez 4 dni pracy udało się mi się przyswoić podstawy, które są wystarczające do kolejnych kroków w naszym projekcie. Podczas kolejnych dni równolegle będę przyswajał dodatkowe informacje na temat języka C++. Szczegółowe informacje na temat moich dni nauki zawarłem w sprawozdaniu naszego pierwszego sprintu tu na wspólnym dysku Google.

**Comment by edek1205** [comment]
Co do Milestone to może być powinniśmy się być w bardziej niż ambitni. ;-)

**Comment by arkaleta** [comment]
Ja zacząłem od samego początku i pracowałem codziennie w krótkich sesjach po ok. 3h. Udało mi się przyswoić podstawy i myślę że jestem w stanie podjąć już jakieś konkretne kroki w naszym projekcie. Na wspólnym dysku Google udostępniłem plik .doc ze szczegółowymi informacjami na temat mojej pracy.

**Comment by Bartek-INPG** [comment]
Z powodu  problemów technicznych nie udało mi się wziąć udziału w podsumowaniu sprintu.
