### ISSUE TITLE
Wybór środowiska programistycznego

### ISSUE THREAD

**Issue by edek1205** [lukaszex/Wolphram-omega#7]
Proszę tutaj o informację o wyniku badania.

**Comment by arkaleta** [comment]
Po zapoznaniu się z tematem zrobiłem krótką ankietę prezentującą kilka wybranych przeze mnie środowisk. Przesłałem ją pozostałym członkom zespołu. Najwięcej głosów uzyskało środowisko Code::Blocks z biblioteką wxWidgets. Załączam link do wyników ankiety oraz wykres. [https://docs.google.com/spreadsheets/d/1FGvshOxVmN2XbIynH3mUUSxPNHwXw46i0BoFqMJ8bUI/edit#gid=1232109128](url)
![image](https://cloud.githubusercontent.com/assets/27811651/25890817/44f492e2-356f-11e7-8687-5b4cdba3a194.png)

**Comment by edek1205** [comment]
Dzięki. Możemy pójść dalej.
